<a href="https://colab.research.google.com/github/tiffanyssy/Healthcare-Feature-Engineering/blob/master/intro_to_ML_with_python_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
from scipy import sparse

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print("x:\n{}".format(x))
print(x)

x:
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
